name: stable-diffusion-webui-docker

services:

  comfy-setup:
    build: ./services/comfy-setup/
    image: comfy-setup:latest
    profiles: ["comfy-setup"]
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - SETUP_DRY_RUN=${SETUP_DRY_RUN:-1} # Default is to run dry run
    volumes:
      - ./data:/data

  comfy:
    profiles: ["comfy"]
    build: ./services/comfy/
    image: comfy:latest
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - CLI_ARGS=
    ports:
      - "8188:8188" # hardcoded in Dockerfile for now
    volumes:
      # - ./services/comfy/extra_model_paths.yaml:/extra_model_paths.yaml:ro,cached
      - ./data:/data:delegated
      - ./output:/output
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]

  comfy-cpu:
    profiles: ["comfy-cpu"]
    build: ./services/comfy/
    image: comfy:latest
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - CLI_ARGS=--cpu
    ports:
      - "8188:8188" # hardcoded in Dockerfile for now
    volumes:
      # - ./services/comfy/extra_model_paths.yaml:/extra_model_paths.yaml:ro,cached
      - ./data:/data:delegated
      - ./output:/output
    stop_signal: SIGKILL
    tty: true