name: stable-diffusion-webui-docker

services:
  download:
    build: ./services/download/
    profiles: ["download"]
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ./data:/data

  auto:
    profiles: ["auto"]
    build: ./services/AUTOMATIC1111
    image: auto:v1.10.1
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - CLI_ARGS=${AUTO_CLI_ARGS}
    ports:
      - "7860:7860" # hardcoded in Dockerfile for now
    volumes:
      - ./data:/data
      - ./output:/output
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]

  comfy:
    profiles: ["comfy"]
    build: ./services/comfy/
    image: comfy:v0.3.39
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - CLI_ARGS=${COMFY_CLI_ARGS}
    ports:
      - "8188:8188" # hardcoded in Dockerfile for now
    volumes:
      # I think we need clearer seperation than just ./data. for example .cache is for python and should not be shared
      - ./data:/data
      # - comfy_data:/data:cached # Or :delegated 
      # Or we can have multiple name vols??? or maybe paths within the name vol???
      # - comfy_config:/data/comfy/config:cached # Or :delegated
      - ./output:/output
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]

volumes:
  comfy_data:

# TODO
# Named volume for plugins? With some manifest that you can edit in case you bork something?
# Version auto1111, use same or similar base images
# Fix Mappings for models `/data/models` and `data/config/comfy/models` the later is created by ComfyManager
# Run everything in an venv
