name: ComfyUI-Docker

services:

  comfy-setup:
    image: ghcr.io/pixeloven/comfyui-docker/comfy-setup:latest
    profiles: ["comfy-setup"]
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - SETUP_DRY_RUN=${SETUP_DRY_RUN:-1} # Default is to run dry run
    volumes:
      - ./data:/data

  comfy-nvidia:
    profiles: ["comfy-nvidia"]
    image: ghcr.io/pixeloven/comfyui-docker/comfy-nvidia:latest
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - COMFY_PORT=${COMFY_PORT:-8188}
      - CLI_ARGS=
    ports:
      - "${COMFY_PORT:-8188}:${COMFY_PORT:-8188}"
    volumes:
      - ./services/comfy/extra_model_paths.yaml:/home/ubuntu/app/extra_model_paths.yaml:ro,cached
      - ./services/comfy/comfy-lock.yaml:/home/ubuntu/app/comfy-lock.yaml:ro,cached
      - ./data:/data:delegated
      - ./output:/output
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]

  comfy-cpu:
    profiles: ["comfy-cpu"]
    image: ghcr.io/pixeloven/comfyui-docker/comfy-cpu:latest
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - COMFY_PORT=${COMFY_PORT:-8188}
      - CLI_ARGS=--cpu
    ports:
      - "${COMFY_PORT:-8188}:${COMFY_PORT:-8188}"
    volumes:
      - ./services/comfy/extra_model_paths.yaml:/home/ubuntu/app/extra_model_paths.yaml:ro,cached
      - ./services/comfy/comfy-lock.yaml:/home/ubuntu/app/comfy-lock.yaml:ro,cached
      - ./data:/data:delegated
      - ./output:/output
    stop_signal: SIGKILL
    tty: true
