name: stable-diffusion-webui-docker

services:
  download:
    build: ./services/download/
    profiles: ["download"]
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ./data:/data

  auto:
    profiles: ["auto"]
    build: ./services/AUTOMATIC1111
    image: auto:v1.10.1
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - CLI_ARGS=${AUTO_CLI_ARGS}
    ports:
      - "7860:7860" # hardcoded in Dockerfile for now
    volumes:
      - ./data:/data
      - ./output:/output
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]

  comfy:
    profiles: ["comfy"]
    build: ./services/comfy/
    image: comfy:v0.3.39
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - CLI_ARGS=${COMFY_CLI_ARGS}
    ports:
      - "8188:8188" # hardcoded in Dockerfile for now
    volumes:
      # - ./comfy/extra_model_paths.yaml:/extra_model_paths.yaml:ro,cached
      - ./data:/data:delegated
      - ./output:/output
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]

  comfy-cpu:
    profiles: ["comfy-cpu"]
    build: ./services/comfy/
    image: comfy:v0.3.39
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - CLI_ARGS=${COMFY_CLI_ARGS:---cpu}
    ports:
      - "8189:8188" # Different port to avoid conflicts
    volumes:
      # - ./comfy/extra_model_paths.yaml:/extra_model_paths.yaml:ro,cached
      - ./data:/data:delegated
      - ./output:/output
    stop_signal: SIGKILL
    tty: true

# Version auto1111, use same or similar base images
# Fix Mappings for models `/data/models` and `data/config/comfy/models` the later is created by ComfyManager
# Run everything in an venv
# IPAdapterPlus
# ONNX
# comfyui-manager by default

# Model/Embeddings
# /data/config/comfy
# /data/config/auto
# /data/config/shared
# Also move /output to /data/output

# Rather than swarm maybe forge? https://github.com/lllyasviel/stable-diffusion-webui-forge
# Also maybe invoke? 
# Should also decide whether this repo is just for image gen in stable or more general AI workflow since some of thje tools also blur and support audio, text etc