name: ComfyUI-Docker
# Any leasons we can learn from InvokeAI?
# https://github.com/invoke-ai/InvokeAI/blob/main/docker/docker-compose.yml

# @todo extra_model_paths.yaml should be compatible with invokeai and have versions for default, invoke, a1111, etc.
# @todo manage top extensions https://github.com/if-ai/ComfyUI-IF_Trellis as one of them
# @todo post install script to install extensions and models https://github.com/microsoft/TRELLIS/pull/30/files

services:

  comfy-setup:
    image: ghcr.io/pixeloven/comfyui-docker/comfy-setup:latest
    profiles: ["comfy-setup"]
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - SETUP_DRY_RUN=${SETUP_DRY_RUN:-1} # Default is to run dry run
    volumes:
      - ./data:/data

  comfy-nvidia:
    profiles: ["comfy-nvidia"]
    image: ghcr.io/pixeloven/comfyui-docker/comfy-nvidia:latest
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - COMFY_PORT=${COMFY_PORT:-8188}
      - CLI_ARGS=
    ports:
      - "${COMFY_PORT:-8188}:${COMFY_PORT:-8188}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./services/comfy/extra_model_paths.yaml:/home/ubuntu/app/extra_model_paths.yaml:ro,cached
      - ./services/comfy/comfy-lock.yaml:/home/ubuntu/app/comfy-lock.yaml:ro,cached
      - ./data:/data:delegated
      - ./output:/output
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]

  comfy-cpu:
    profiles: ["comfy-cpu"]
    image: ghcr.io/pixeloven/comfyui-docker/comfy-cpu:latest
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - COMFY_PORT=${COMFY_PORT:-8188}
      - CLI_ARGS=--cpu
    ports:
      - "${COMFY_PORT:-8188}:${COMFY_PORT:-8188}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro  
      - ./services/comfy/extra_model_paths.yaml:/home/ubuntu/app/extra_model_paths.yaml:ro,cached
      - ./services/comfy/comfy-lock.yaml:/home/ubuntu/app/comfy-lock.yaml:ro,cached
      - ./data:/data:delegated
      - ./output:/output
    stop_signal: SIGKILL
    tty: true
