name: stable-diffusion-webui-docker

services:

  comfy-setup:
    build: ./services/comfy-setup/
    image: comfy-setup:latest
    profiles: ["comfy-setup"]
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - CLI_ARGS=${SETUP_CLI_ARGS:-""}
    volumes:
      - ./data:/data

  comfy:
    profiles: ["comfy"]
    build: ./services/comfy/
    image: comfy:latest
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      # - CLI_ARGS=${COMFY_CLI_ARGS:-""} # This doesn't work
    ports:
      - "8188:8188" # hardcoded in Dockerfile for now
    volumes:
      # - ./comfy/extra_model_paths.yaml:/extra_model_paths.yaml:ro,cached
      - ./data:/data:delegated
      - ./output:/output
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]

# Version auto1111, use same or similar base images
# Fix Mappings for models `/data/models` and `data/config/comfy/models` the later is created by ComfyManager
# Run everything in an venv
# IPAdapterPlus
# ONNX
# comfyui-manager by default

# Model/Embeddings
# /data/config/comfy
# /data/config/auto
# /data/config/shared
# Also move /output to /data/output

# Rather than swarm maybe forge? https://github.com/lllyasviel/stable-diffusion-webui-forge
# Also maybe invoke? 
# Should also decide whether this repo is just for image gen in stable or more general AI workflow since some of thje tools also blur and support audio, text etc