services:

  comfyui:
    build: ./services/ComfyUI/
    image: comfyui
    # user: ${PUID:-1000}:${PGID:-1000}
    # environment:
    #   - PUID=${PUID:-1000}
    #   - PGID=${PGID:-1000}
    #   - CLI_ARGS=
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/data
      - ./output:/output
    ports:
      - "7860:7860"
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${DEVICE_DRIVER:-nvidia}
              device_ids: ['0']
              capabilities: [compute, utility]
    restart: unless-stopped

